### PR TITLE
Windows: update zeromq libs + arm64 support

### PR DESCRIPTION
**Pull request by jeroen**
Copy over from rzmq package.

### CODE REVIEW

**Comment by jeroen** [comment]
Hmm not sure what is going wrong here. Should be a trivial update.

**Comment by mschubert** [comment]
Thanks! I'll take a closer look tomorrow

**Comment by mschubert** [comment]
Hi @jeroen, did you compile the DRAFT API in for the `R=4.3` libzmq binary (`-DZMQ_BUILD_DRAFT_API=1`)?

I remember we talked about this a while ago, and it was included in the previous `zeromq` binary for Windows

**Comment by jeroen** [comment]
Ahhh that would be it. Let me look at it again.

**Comment by mschubert** [comment]
Looking at  this more closely, I think you `libzmq` is fine but your `cppzmq` header is outdated: [MINGW is `4.7.1`](https://github.com/msys2/MINGW-packages/blob/f4f90a18b066fb56c0986faa56002c1228c9b7bc/mingw-w64-zeromq/PKGBUILD#L7C17-L7C17) but current [`cppzmq` is `4.10.0`](https://github.com/zeromq/cppzmq/releases)

**Comment by mschubert** [comment]
And with more testing, I think that:

*  `-DZMQ_BUILD_DRAFT_API=1` in `PKG_CPPFLAGS` is not respected, needs to be in `PKG_CFLAGS`
* `-Icppzmq` needs to be set in `PKG_CFLAGS` and `PKG_CPPFLAGS` to actually use the clustermq-internal header
* The DRAFT API is actually missing from `libzmq`

**Comment by mschubert** [comment]
I've added much more detailed messages now, e.g. [here](https://github.com/mschubert/clustermq/actions/runs/6518883666/job/17704790881):

```
common.h:26:2: error: #error clustermq needs libzmq>=4.3.0 and cppzmq>=4.10.0 with DRAFT enabled
common.h:18:55: note: '#pragma message: libzmq version is: 4.3.4'
common.h:20:61: note: '#pragma message: cppzmq version is: 4.10.0'
common.h:24:17: note: '#pragma message: DRAFT API is missing'
```

**Comment by jeroen** [comment]
Thanks! I have just deployed the fixed binaries: https://github.com/r-windows/ucrt-libs/commit/f870993f2c5b358d6837a5ad792c78d1292d52f4. So hopefully it works now. Can you try to trigger a rebuild?

**Comment by mschubert** [comment]
Working now :tada:
Thanks a lot!

**Pull request merged**
